### ISSUE TITLE
`to_parquet` does not write a separate file for each partition when only a subset of columns is used during reading

### ISSUE THREAD

**Issue by xichens** [dask/dask-expr#1103] opened 2024-07-11 19:33 UTC
**Describe the issue**:
I have a parquet file with 13 row groups. I loaded it with `dd.read_parquet(split_row_groups=True)` into 13 partitions. Then when I re-wrote the data back to disk with `.to_parquet`, it only wrote 4 files instead of 13.

This ONLY happened when I use `columns` to select a subset of columns when `read_parquet`. If I read the whole data, it behaved as expected.

Also if I set `dask.config.set({"dataframe.query-planning": False})`, it also worked as expected.

**Minimal Complete Verifiable Example**:

```python
import dask.dataframe as dd

# without columns arg, it worked fine.
# df = dd.read_parquet(data_path, split_row_groups=True)
df = dd.read_parquet(data_path, split_row_groups=True, columns=["id0"])

df.to_parquet(output_path, write_metadata_file=True)

from os import listdir

listdir(output_path)
```
With `columns=["id0"]`, it wrote
```
['_common_metadata',
 '_metadata',
 'part.3.parquet',
 'part.2.parquet',
 'part.0.parquet',
 'part.1.parquet']
```
Without, it wrote
```
['_common_metadata',
 'part.4.parquet',
 'part.5.parquet',
 'part.7.parquet',
 'part.6.parquet',
 '_metadata',
 'part.3.parquet',
 'part.12.parquet',
 'part.2.parquet',
 'part.9.parquet',
 'part.0.parquet',
 'part.11.parquet',
 'part.1.parquet',
 'part.10.parquet',
 'part.8.parquet']
```

**Environment**:

- Dask version: 2024.7.0
- Dask-expr version: 1.1.7
- Python version: 3.9.6
- Operating System: MacOS

**Comment by fjetter** [comment] 2024-07-12 10:03
This is intended behavior. The column projection is reducing the size of every individual partition and the optimizer is squashing those to avoid fragmentation.

**Comment by xichens** [comment] 2024-07-12 14:22
> This is intended behavior. The column projection is reducing the size of every individual partition and the optimizer is squashing those to avoid fragmentation.

Thanks for the reply. That makes sense. Where can I read about the criteria that the optimizer uses to determine the number of files to write (or is this configurable)? The above example is a simplified version to reproduce my situation. In my actual case, there are some `map_partitions` calls to create new cols on top of the selected cols before writing out the results. The actual data to be written is close to the full input data regarding physical size. But I also noticed less files were written than the number of partitions. That's why I'm curious how that is determined.

On a side note, I guess my previous confusion mainly came from the note under the documentation page for `to_parquet` which says
> Each partition will be written to a separate file.

If that's no longer the case, I feel it is helpful to know how many separate file users should expect, as usually that will also be the number partitions the new data will be loaded into.

**Comment by phofl** [comment] 2024-07-15 08:27
> If that's no longer the case,

This is still the case, the main difference is that read_parquet does not necessarily create one file per partition anymore.

You can read about this here:

https://docs.dask.org/en/stable/dataframe-optimizer.html#optimization-steps

in the automatically resizing partitions sections. Feedback welcome!

**Comment by phofl** [comment] 2024-08-12 08:21
Closing this here, please feel free to ping if this is a bug

**Closed by phofl** 2024-08-12 08:21 UTC
